backend:
  name: my-custom-backend

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Yazılar"
    folder: "posts"
    create: true
    extension: json   # <--- BUNU EKLE
    format: json      # <--- BUNU EKLE
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "İçerik", name: "body", widget: "text" }
      - { label: "Yazar", name: "author", widget: "string", required: false }