backend:
  name: my-custom-backend

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Yazılar"
    folder: "posts"
    create: true
    extension: json
    format: json
    fields:
      - { label: "Başlık", name: "title", widget: "string", required: true }
      - { label: "Kapak Fotoğrafı", name: "image", widget: "image", required: false }
      - { label: "İçerik", name: "body", widget: "markdown", required: true }
      - { label: "Yazar", name: "author", widget: "string", required: true }